services:
  server:
    container_name: my-server
    build: . 
    ports:
      - "23232:23232"
    networks:
      - postgres
    depends_on:
      - db

  db:
    container_name: postgres-database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 246224682
      POSTGRES_DB: postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres: